name: unchained
description: "A new Flutter project."

publish_to: 'none'

version: 1.2.2+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  fluent_ui:
  bitsdojo_window:
  toml:
  cupertino_icons: ^1.0.8
  url_launcher:
  shared_preferences: 
  dio: ^5.0.0
  flutter_markdown: 
  archive: 
  path_provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rathole.exe
    - assets/app_icon.ico