name: unchained
description: "A new Flutter project."

publish_to: 'none'

version: 1.2.3+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  fluent_ui:
  bitsdojo_window:
  toml:
  cupertino_icons: 
  url_launcher:
  shared_preferences: 
  dio: 
  flutter_markdown_plus: 
  archive: 
  path_provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rathole/rathole.exe
    - assets/app_icon.ico