name: unchained
description: "A new Flutter project."

publish_to: 'none'

version: 1.3.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  toml: 
  url_launcher:
  shared_preferences: 
  dio: 
  flutter_markdown_plus: 
  archive: 
  path_provider: 
  flutter_colorpicker: 
  material_color_utilities: 
  window_manager: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rathole/rathole.exe
    - assets/app_icon.ico